# Copy or symlink /etc/nixos/hardware-configuration.nix here.
# This flake requires hardware-configuration.nix stored alongside config.nix for a specific host to work
# It should've been generated by nixos-generate-config